---
detectors:
  IrresponsibleModule:
    enabled: false
  BooleanParameter:
    exclude:
    - Navigator::Menu#respond_to_missing?
  ControlParameter:
    exclude:
    - Navigator::Menu#activate_item_attributes!
  DataClump:
    exclude:
    - Navigator::Menu
  DuplicateMethodCall:
    exclude:
    - Navigator::Menu#activate_item_attributes!
  LongParameterList:
    enabled: false
  MissingSafeMethod:
    exclude:
    - Navigator::Menu
    - Navigator::Tag
  TooManyStatements:
    exclude:
    - initialize
    - Navigator::Menu#add
  UtilityFunction:
    exclude:
    - Navigator::Menu#activate_item_attributes!
    - Navigator::Tag#expand_data_attributes!
